### ISSUE TITLE
Outdated Documentation

### ISSUE THREAD

**Issue by mHash1m** [Effective-Quadratures/equadratures#262]
It seems that the documentation mentions [plotting utilities](https://equadratures.org/_modules/equadratures/plot.html) but I can't find them in the code base, or use them with the package. They are similarly present in the [Parameter documentation](https://equadratures.org/_documentation/parameter.html#equadratures.parameter.Parameter.plot_orthogonal_polynomials) as well. I'm not sure whats the actual source of this documentation on the equadratures website to PR and fix this.

**Comment by ascillitoe** [comment]
Hi @mHash1m the plotting utilities were previously in `feature_docs`. However, I have just merged them into `develop`. If you are going through the documentation or tutorials I would use `develop` for now. Hopefully, we'll be merging `develop` into `master` and releasing a new version in the coming weeks!

Thanks for pointing this out :)

**Comment by mHash1m** [comment]
Alright, Thanks!
