### ISSUE TITLE
Adding another class of distributions.

### ISSUE THREAD

**Issue by Simardeep27** [Effective-Quadratures/equadratures#264]
This is a feature request for adding another class of distributions for <code>equadratures.distributions</code>.

Supporting Distributions like:
<ul>
<li>Binomial Distribution</li>
<li>Poisson Distribution</li>
<li>Multinomial Distribution</li>
</ul>

Would work on this if approved.

**Comment by psesh** [comment]
Sure @Simardeep27 that would be a welcome addition to the develop `branch` -- many thanks! The only recommendation would be to also weave in a few test cases in `test_distributions.py`.

**Comment by Simardeep27** [comment]
Thanks a lot for the opportunity. 
Will make a PR as soon as possible.

**Comment by psesh** [comment]
Cheers! Also feel free to comment about it once committed on the [discourse](https://discourse.equadratures.org/).

**Comment by psesh** [comment]
An opportunity for code improvement; not a bug, thus closed.
