### ISSUE TITLE
Dependency Issues

### ISSUE THREAD

**Issue by mdonnelly1** [Effective-Quadratures/equadratures#273]
Currently the setup specifies a dependency of 'scipy >= 0.15.0'. However the optimisation module imports scipy.linalg.null_space which was added later (appears to have been introduced in Scipy 1.1.0: https://docs.scipy.org/doc/scipy/reference/release.1.1.0.html).

Not that it's an issue for you but our internal python environment is currently limited to scipy 0.18.1 so the fix for us isn't as straightforward as just updating the scipy package we use. On our local copy of the code I've needed to comment out the import and manually implement the null_space function. My preference for a (somewhat ugly) fix would probably be to leave the dependency as is but to wrap the import in a try/except with a local implementation of null_space defined if it doesn't work.

Also I think datasets.py imports requests which isn't currently listed as a dependency. It works with requests 2.11.1.

**Comment by ncywong** [comment]
Hi @mdonnelly1 , I have pushed a commit that re-implements the null_space method from Scipy on https://github.com/Effective-Quadratures/equadratures/commit/4bbd09a1bc53a172f77b5315afa60ef29bee4245 . Hopefully that should work with scipy 0.18.1.

**Comment by ascillitoe** [comment]
Hi @mdonnelly1, slightly random (but related) question, what is the latest python version you guys have reliable access to?

**Comment by mdonnelly1** [comment]
@ncywong wow that was quick - thanks! I'll have a look shortly.

@ascillitoe currently 3.5.1 and Numpy 1.11.2. I think there are improvements on the horizon so hopefully we'll get a bit more up to date soon!

**Comment by ascillitoe** [comment]
@mdonnelly1 good to know, thanks!
